### ISSUE TITLE
Pages with "load more comments" trigger 100% cpu

### ISSUE THREAD

**Issue by sanderssj** [Math-e/old-reddit-images#1]
Pages with a "load more comments" link cause the extension to start using 100% cpu and constantly grow memory usage after about 10 seconds or so. Firefox 130.0.1, OS X 14.6.1.
<img width="571" alt="old-reddit-images-profile" src="https://github.com/user-attachments/assets/d0579886-9772-48d0-afbf-1ea961cc4b1b">

**Comment by Math-e** [comment]
I couldn't find a significant resource usage caused by the extension on my Windows and Linux machines. Which hardware is it?
Anyways, I made a few improvements to the code. Can you test the latest code release as a debug extension?

**Comment by sanderssj** [comment]
I am running on the M2 arch. These changes do appear to fix the problem. Thanks!
